-- =============================================================================
-- CONSOLIDADO — NADA PENDENTE.
-- =============================================================================
--
-- Este arquivo não é uma migração. É um pacote de emergência: quando uma
-- execução do RECRIAR-DO-ZERO.sql deixa um trecho do meio sem efeito, as
-- migrações que faltaram são copiadas para cá, na ordem certa, para serem
-- rodadas em uma tacada. O verificador (scripts/verificar-migracoes.js) o
-- ignora de propósito — quem manda são os arquivos de fase.
--
-- HOJE ELE ESTÁ VAZIO, e vazio é o estado normal dele.
--
-- O QUE ELE GUARDOU, E POR QUE SAIU (30/09/2026)
-- ----------------------------------------------
-- Ele carregava 765 linhas com nove fases — AA a AJ — copiadas em 25/08/2026,
-- quando o banco vivia num projeto do Supabase e um trecho do meio da
-- recriação não teve efeito. O cabeçalho dizia, com todas as letras:
-- "SITUACAO EM 25/08/2026, no projeto novo do Supabase".
--
-- Duas coisas aconteceram depois:
--
--   o Supabase saiu (agosto/2026). O banco é um PostgreSQL em Docker, e o
--   caminho de aplicar migração passou a ser `npm run migracoes:aplicar`, não
--   colar SQL num painel web;
--
--   as nove fases foram aplicadas. Conferido em 30/09/2026 contra a tabela
--   `schema_migracoes` do banco local: 9 de 9 presentes. E a lista de
--   pendências do VPS é outra (fases CX, CZ, DC, DD, DJ, DK) — nenhuma destas.
--
-- Um pacote de emergência que descreve uma emergência resolvida, num banco que
-- não existe mais, é pior do que um arquivo vazio: quem o abrir com pressa vai
-- rodar 765 linhas de SQL achando que está consertando algo.
--
-- COMO ELE VOLTA A TER CONTEÚDO
-- -----------------------------
-- Rode `npm run migracoes`. Se ele acusar fase que está no disco e não no
-- banco, copie o SQL dela para cá com a linha de origem:
--
--     -- >>> fase-xx-nome-da-fase.sql
--
-- É essa linha que scripts/test-verificador-migracoes.js usa para conferir que
-- o pacote não inventou comando nem esqueceu nenhum. Sem ela, o teste passa a
-- exigir que o arquivo esteja vazio — que é onde ele está agora.
--
-- =============================================================================
