/**
 * O LEIAUTE OFICIAL DA EFD-ICMS/IPI — campo por campo, registro por registro.
 *
 * DE ONDE VEIO, e por que isto é código e não um PDF numa pasta
 * ------------------------------------------------------------
 * Extraído do Guia Prático da EFD-ICMS/IPI versão 3.2.2, atualização de 11 de
 * fevereiro de 2026, publicado pela Receita Federal no portal do SPED
 * (http://sped.rfb.gov.br/item/show/8112). É o Guia em vigor para o leiaute
 * versão 020 — o mesmo COD_VER que aparece no registro 0000 da escrituração
 * de agosto de 2026 desta empresa.
 *
 * O PDF tem 362 páginas e não dá para versionar, revisar em diff nem consultar
 * em tempo de execução. O que o sistema precisa dele é uma coisa só: a ORDEM
 * e a IDENTIDADE dos campos de cada registro. Isso cabe aqui.
 *
 * COMO ISTO FOI CONFERIDO — e é a parte que importa
 * -------------------------------------------------
 * A escrituração de agosto de 2026 foi aceita pela SEFAZ. Ela usa 40
 * registros distintos, e lib/sped-registros.js guarda quantos campos cada um
 * daqueles registros tinha NO ARQUIVO REAL. A contagem daqui bate com a de lá
 * em 40 de 40 — é o que scripts/test-sped-leiaute.js cobra, e é a
 * única prova disponível de que a leitura do PDF não inventou nem perdeu campo.
 *
 * Quatro defeitos de extração foram achados por essa conferência, e nenhum
 * deles era visível de outra forma:
 *
 *   1. O Guia escreve nome de campo COM ACENTO em nove lugares. O registro
 *      E210 tem "VL_RETENÇAO_ST" e "VL_DEDUÇÕES_ST"; o nome de verdade é
 *      ASCII. O extrator não reconhecia a linha, e os oito campos seguintes
 *      caíam com ela — E210 vinha com 7 campos em vez de 15.
 *   2. O campo 10 do E116 e do E250 é escrito "MES_REF*", com o asterisco da
 *      nota de rodapé dentro do nome. Os dois vinham com 9 campos em vez de 10.
 *   3. O campo 02 do G990 tem o tipo colado no traço: "N- -".
 *   4. No PDF, a célula de descrição desce uma linha em relação ao número do
 *      campo: no 0000, o "C 004" do campo 01 (REG) aparece na linha que começa
 *      com "02 COD_VER". Ler o tipo da linha do próprio campo deslocaria TODOS
 *      os tipos em um. Tamanho errado num gerador de SPED dá arquivo rejeitado
 *      ou, pior, aceito com dado truncado.
 *
 * Por causa do (4), tipo/tamanho/decimais NÃO são lidos da linha do campo: são
 * colhidos na ordem do documento e casados com os campos na ordem da coluna
 * Nº, e só quando as duas contagens batem. Quando não batem, o registro fica
 * SEM TIPO em vez de ficar com tipo chutado — ver SEM_TIPO.
 *
 * O QUE ESTE ARQUIVO NÃO TEM
 * --------------------------
 * A COLUNA "OBRIG" (O / OC / N) ficou fora de propósito. Ela sofre do mesmo
 * deslocamento do item (4) e, pior, em dezenas de registros a obrigatoriedade
 * real está na prosa acima da tabela ("obrigatório se o declarante for...").
 * Um campo marcado "obrigatório" por leitura torta de PDF faria o gerador
 * recusar uma escrituração válida. Quem precisar disso lê o Guia.
 *
 * NÃO TEM AS TABELAS EXTERNAS (5.1.1 de ajustes, 5.4 de obrigações, 4.3.2 de
 * CFOP) nem as REGRAS DE VALIDAÇÃO cruzada. Isto é o leiaute, não o validador.
 *
 * E NÃO É UM GERADOR. Ter o leiaute não produz arquivo: dez dos 40 registros
 * usados em agosto não têm origem nenhuma neste sistema (ver `semFonte` em
 * lib/sped-registros.js), e entre eles está o bloco E inteiro — a apuração do
 * imposto. Esta é a peça que faltava, não a última.
 *
 * O FORMATO
 * ---------
 * Um registro por linha, os campos separados por "|", na ordem do leiaute:
 *
 *     NOME:tipo+tamanho[*][.decimais]
 *
 *     REG:C4          texto de 4 posições
 *     COD_VER:N3*     numérico, 3 posições, tamanho variável
 *     VL_DOC:N-.2     numérico sem tamanho fixo, 2 decimais
 *     DT_DOC:N8*      data (o Guia classifica data como N; ver `tipo`)
 *
 * Registro em SEM_TIPO aparece só com os nomes, sem ":".
 *
 * O arquivo da EFD é delimitado por "|", NÃO é de posição fixa — o tamanho é
 * limite de validação, não gabarito de preenchimento com zeros à esquerda.
 */

// A versão do Guia de onde isto saiu, e o leiaute que ele descreve. Se um dia
// subir para 021, o COD_VER do 0000 muda e este arquivo tem de ser refeito.
const GUIA_VERSAO = '3.2.2';
const GUIA_ATUALIZACAO = '2026-02-11';
const LEIAUTE_VERSAO = '020';
const GUIA_URL = 'http://sped.rfb.gov.br/item/show/8112';

// Registros cujo tipo/tamanho não foi extraído com segurança: a tabela deles
// no PDF está desalinhada de um jeito que a conferência de contagem não
// aprovou. Os NOMES e a ORDEM valem; tipo e tamanho, não.
const SEM_TIPO = ["0300","1010","1110","1210","1601","1922","1923","B020","B035","B460","B470","B500","C113","C165","C177","C179","C181","C300","C420","C490","C500","C510","C591","C600","C610","C690","C790","C800","D100","D190","D300","D410","D610","D690","D696","D730","D750","E113","E240","E310","E313","G126","K275","K280"];

// REGISTROS COM NOME DE CAMPO DUVIDOSO — e nenhum deles é dos 40 que esta
// empresa usa, o que é o que torna este arquivo utilizável.
//
// O nome vem PARTIDO no PDF quando não cabe na coluna, e o resto dele cai na
// coluna 0 da linha seguinte: "VL_BC_ICMS_" + "ST" no C190,
// "VL_SLD_CREDOR_TRA" + "NSPORTAR" no E110. A remontagem resolveu a maioria —
// os dois exemplos acima são justamente os do C190 e do E110, sem os quais a
// apuração em lib/sped-apuracao.js sairia com nome de campo errado.
//
// Nestes sobrou nome terminando em "_" ou nome repetido dentro do registro, e
// repetido é impossível: é sinal de que a remontagem não pegou tudo. O G125
// chegou a ter QUATRO campos chamados "VL_IMOB_ICMS_".
//
// NÃO CONSTRUIR SOBRE ESTES sem conferir no Guia. São dos blocos que este
// negócio não usa: combustível, energia, transporte, ISS e produção.
//
// E A CONFERÊNCIA DE CONTAGEM NÃO PEGA ISSO: com o nome truncado, o número de
// campos continua certo. Quem pega é a unicidade do nome.
const NOMES_SUSPEITOS = ["0221","0500","1391","B020","B030","B470","C130","C181","C185","C330","C430","C480","C815","C880"];

// Nome que aparece DUAS vezes no mesmo registro, no próprio Guia, de propósito.
// Conferido caso a caso — não é resíduo de extração.
const DUPLICADOS_LEGITIMOS = {"C170":["ALIQ_PIS","ALIQ_COFINS"]};

// Nomes que o Guia escreve com acento, e que aqui estão em ASCII — que é como
// eles entram no arquivo.
const NOMES_ACENTUADOS_NO_GUIA = [
  "0500.NIVEL (o guia escreve NÍVEL)",
  "1391.SAIDAS (o guia escreve SAÍDAS)",
  "E210.VL_RETENCAO_ST (o guia escreve VL_RETENÇAO_ST)",
  "E210.VL_DEDUCOES_ST (o guia escreve VL_DEDUÇÕES_ST)",
  "E310.VL_DEDUCOES_DIFAL (o guia escreve VL_DEDUÇÕES_DIFAL)",
  "E310.VL_DEDUCOES_FCP (o guia escreve VL_DEDUÇÕES_FCP)",
  "K235.DT_SAIDA (o guia escreve DT_SAÍDA)",
  "K260.DT_SAIDA (o guia escreve DT_SAÍDA)",
  "K260.QTD_SAIDA (o guia escreve QTD_SAÍDA)"
];

const CRU = {
  '0000': 'REG:C4|COD_VER:N3*|COD_FIN:N1|DT_INI:N8*|DT_FIN:N8*|NOME:C100|CNPJ:N14*|CPF:N11*|UF:C2*|IE:C14|COD_MUN:N7*|IM:C-|SUFRAMA:C9*|IND_PERFIL:C1|IND_ATIV:N1', // usado em agosto/2026
  '0001': 'REG:C4|IND_MOV:N1', // usado em agosto/2026
  '0002': 'REG:C4|CLAS_ESTAB_IND:N2',
  '0005': 'REG:C4|FANTASIA:C60|CEP:N8*|END:C60|NUM:C10|COMPL:C60|BAIRRO:C60|FONE:C11|FAX:C11|EMAIL:C-', // usado em agosto/2026
  '0015': 'REG:C4|UF_ST:C2*|IE_ST:C14',
  '0100': 'REG:C4|NOME:C100|CPF:N11*|CRC:C15|CNPJ:N14*|CEP:N8*|END:C60|NUM:C10|COMPL:C60|BAIRRO:C60|FONE:C11|FAX:C11|EMAIL:C-|COD_MUN:N7*', // usado em agosto/2026
  '0150': 'REG:C4|COD_PART:C60|NOME:C100|COD_PAIS:N5|CNPJ:N14*|CPF:N11*|IE:C14|COD_MUN:N7*|SUFRAMA:C9*|END:C60|NUM:C10|COMPL:C60|BAIRRO:C60', // usado em agosto/2026
  '0175': 'REG:C4|DT_ALT:N8*|NR_CAMPO:C2|CONT_ANT:C100',
  '0190': 'REG:C4|UNID:C6|DESCR:C-', // usado em agosto/2026
  '0200': 'REG:C4|COD_ITEM:C60|DESCR_ITEM:C-|COD_BARRA:C-|COD_ANT_ITEM:C60|UNID_INV:C6|TIPO_ITEM:N2|COD_NCM:C8*|EX_IPI:C3|COD_GEN:N2*|COD_LST:C5|ALIQ_ICMS:N6.2|CEST:N7*', // usado em agosto/2026
  '0205': 'REG:C4|DESCR_ANT_ITEM:C-|DT_INI:N8*|DT_FIM:N8*|COD_ANT_ITEM:C60',
  '0206': 'REG:C4|COD_COMB:C-',
  '0210': 'REG:C4|COD_ITEM_COMP:C60|QTD_COMP:N-.6|PERDA:N-.4',
  '0220': 'REG:C4|UNID_CONV:C6|FAT_CONV:N-.6|COD_BARRA:C-',
  '0221': 'REG:C4|COD_ITEM_:C60|QTD_CONTIDA:N-.6',
  '0300': 'REG|COD_IND_BEM|IDENT_MERC|DESCR_ITEM|COD_PRNC|COD_CTA|NR_PARC',
  '0305': 'REG:C4*|COD_CCUS:C60|FUNC:C-|VIDA_UTIL:N3',
  '0400': 'REG:C4|COD_NAT:C10|DESCR_NAT:C-',
  '0450': 'REG:C4|COD_INF:C6|TXT:C-', // usado em agosto/2026
  '0460': 'REG:C4|COD_OBS:C6|TXT:C-',
  '0500': 'REG:C4*|DT_ALT:N8*|COD_:C2*|IND_CTA:C1*|NIVEL:N5|COD_CTA:C60|NOME_CTA:C60',
  '0600': 'REG:C4*|DT_ALT:N8*|COD_CCUS:C60|CCUS:C60',
  '0990': 'REG:C4|QTD_LIN_0:N-', // usado em agosto/2026
  '1001': 'REG:C4|IND_MOV:N1*', // usado em agosto/2026
  '1010': 'REG|IND_EXP|IND_CCRF|IND_COMB|IND_USINA|IND_VA|IND_EE|IND_CART|IND_FORM|IND_AER|IND_GIAF1|IND_GIAF3|IND_GIAF4|IND_REST_RESSARC', // usado em agosto/2026
  '1100': 'REG:C4|IND_DOC:N1*|NRO_DE:C14|DT_DE:N8*|NAT_EXP:N1*|NRO_RE:N12|DT_RE:N8*|CHC_EMB:C18|DT_CHC:N8*|DT_AVB:N8*|TP_CHC:N2*|PAIS:N3',
  '1105': 'REG:C4|COD_MOD:C2*|SERIE:C3|NUM_DOC:N9|CHV_NFE:N44*|DT_DOC:N8*|COD_ITEM:C60',
  '1110': 'REG|COD_PART|COD_MOD',
  '1200': 'REG:C4|COD_AJ_APUR:C8*|SLD_CRED:N-.2|CRED_APR:N-.2|CRED_RECEB:N-.2|CRED_UTIL:N-.2|SLD_CRED_FIM:N-.2',
  '1210': 'REG|TIPO_UTIL|NR_DOC|VL_CRED_UTIL',
  '1250': 'REG:C4|VL_CREDITO_ICMS_OP:N-.2|VL_ICMS_ST_REST:N-.2|VL_FCP_ST_REST:N-.2|VL_ICMS_ST_COMPL:N-.2|VL_FCP_ST_COMPL:N-.2',
  '1255': 'REG:C4|COD_MOT_REST_COMPL:C5*.2|VL_CREDITO_ICMS_OP_MOT:N-.2|VL_ICMS_ST_REST_MOT:N-.2|VL_FCP_ST_REST_MOT:N-.2|VL_ICMS_ST_COMPL_MOT:N-.2|VL_FCP_ST_COMPL_MOT:N-.2',
  '1300': 'REG:C4|COD_ITEM:C60|DT_FECH:N8*|ESTQ_ABERT:N-.3|VOL_ENTR:N-.3|VOL_DISP:N-.3|VOL_SAIDAS:N-.3|ESTQ_ESCR:N-.3|VAL_AJ_PERDA:N-.3|VAL_AJ_GANHO:N-.3|FECH_FISICO:N-.3',
  '1310': 'REG:C4|NUM_TANQUE:C3|ESTQ_ABERT:N-.3|VOL_ENTR:N-.3|VOL_DISP:N-.3|VOL_SAIDAS:N-.3|ESTQ_ESCR:N-.3|VAL_AJ_PERDA:N-.3|VAL_AJ_GANHO:N-.3|FECH_FISICO:N-.3|CAP_TANQUE:N6',
  '1320': 'REG:C4|NUM_BICO:N-|NR_INTERV:N-|MOT_INTERV:C50|NOM_INTERV:C30|CNPJ_INTERV:N14*|CPF_INTERV:N11*|VAL_FECHA:N-.3|VAL_ABERT:N-.3|VOL_AFERI:N-.3|VOL_VENDAS:N-.3',
  '1350': 'REG:C4|SERIE:C-|FABRICANTE:C60|MODELO:C-|TIPO_MEDICAO:C1',
  '1360': 'REG:C4|NUM_LACRE:C20|DT_APLICACAO:N8*',
  '1370': 'REG:C4|NUM_BICO:N3|COD_ITEM:C60|NUM_TANQUE:C3',
  '1390': 'REG:C4|COD_PROD:N2*',
  '1391': 'REG:C4|DT_REGISTRO:C8*|QTD_MOID:N-.2|ESTQ_INI:N-.2|QTD_PRODUZ:N-.2|ENT_ANID_HID:N-.2|OUTR_ENTR:N-.2|PERDA:N-.2|CONS:N-.2|SAI_ANI_HID:N-.2|SAIDAS:N-.2|ESTQ_FIN:N-.2|ESTQ_INI_MEL:N-.2|PROD_DIA_MEL:N-.2|UTIL_MEL:N-.2|PROD_ALC_MEL:N-.2|OBS:C-|COD_ITEM:C60|TP_RESIDUO:N2*|QTD_RESIDUO:N-.2|QTD_RESIDUO_:N-.2|QTD_RESIDUO_:N-.2|QTD_RESIDUO_CANA:N-.2',
  '1400': 'REG:C4|COD_ITEM_IPM:C60|MUN:N7*|VALOR:N-.2',
  '1500': 'REG:C4|IND_OPER:C1*|IND_EMIT:C1*|COD_PART:C60|COD_MOD:C2*|COD_SIT:N2*|SER:C4|SUB:N3|COD_CONS:C2*|NUM_DOC:N9|DT_DOC:N8*|DT_E_S:N8*|VL_DOC:N-.2|VL_DESC:N-.2|VL_FORN:N-.2|VL_SERV_NT:N-.2|VL_TERC:N-.2|VL_DA:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|VL_ICMS_ST:N-.2|COD_INF:C6|VL_PIS:N-.2|VL_COFINS:N-.2|TP_LIGACAO:N1*|COD_GRUPO_TENSAO:C2*',
  '1510': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|COD_CLASS:N4*|QTD:N-.3|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2|CST_ICMS:N3*|CFOP:N4*|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|ALIQ_ST:N-.2|VL_ICMS_ST:N-.2|IND_REC:C1*|COD_PART:C60|VL_PIS:N-.2|VL_COFINS:N-.2|COD_CTA:C-',
  '1600': 'REG:C4|COD_PART:C60|TOT_CREDITO:N-|TOT_DEBITO:N-',
  '1601': 'REG|COD_PART_IP|COD_PART_IT|TOT_VS|TOT_ISS|TOT_OUTROS',
  '1700': 'REG:C4|COD_DISP:C2*|COD_MOD:C2*|SER:C4|SUB:C3|NUM_DOC_INI:N12|NUM_DOC_FIN:N12|NUM_AUT:N60',
  '1710': 'REG:C4|NUM_DOC_INI:N12|NUM_DOC_FIN:N12',
  '1800': 'REG:C4*|VL_CARGA:N-.2|VL_PASS:N-.2|VL_FAT:N-.2|IND_RAT:N8.6|VL_ICMS_ANT:N-.2|VL_BC_ICMS:N-.2|VL_ICMS_APUR:N-.2|VL_BC_ICMS_APUR:N-.2|VL_DIF:N-.2',
  '1900': 'REG:C4|IND_APUR_ICMS:C1*|DESCR_COMPL_OUT_APUR:C-',
  '1910': 'REG:C4|DT_INI:N8*|DT_FIN:N8*',
  '1920': 'REG:C4|VL_TOT_TRANSF_DEBITOS_OA:N-.2|VL_TOT_AJ_DEBITOS_OA:N-.2|VL_ESTORNOS_CRED_OA:N-.2|VL_TOT_TRANSF_CREDITOS_OA:N-.2|VL_TOT_AJ_CREDITOS_OA:N-.2|VL_ESTORNOS_DEB_OA:N-.2|VL_SLD_CREDOR_ANT_OA:N-.2|VL_SLD_APURADO_OA:N-.2|VL_TOT_DED:N-.2|VL_ICMS_RECOLHER_OA:N-.2|VL_SLD_CREDOR_TRANSP_OA:N-.2|DEB_ESP_OA:N-.2',
  '1921': 'REG:C4|COD_AJ_APUR:C8*|DESCR_COMPL_AJ:C-|VL_AJ_APUR:N-.2',
  '1922': 'REG|NUM_DA|NUM_PROC|IND_PROC|PROC|TXT_COMPL',
  '1923': 'REG|COD_PART|COD_MOD|SER|SUB|NUM_DOC|DT_DOC|COD_ITEM|VL_AJ_ITEM',
  '1925': 'REG:C4|COD_INF_ADIC:C8*|VL_INF_ADIC:N-.2|DESCR_COMPL_AJ:C-',
  '1926': 'REG:C4|COD_OR:C3*|VL_OR:N-.2|DT_VCTO:N8*|COD_REC:C-|NUM_PROC:C60|IND_PROC:C1*|PROC:C-|TXT_COMPL:C-|MES_REF:N6*',
  '1960': 'REG:C4|IND_AP:N2*|G1_01:N-.2|G1_02:N-.2|G1_03:N-.2|G1_04:N-.2|G1_05:N-.2|G1_06:N-.2|G1_07:N-.2|G1_08:N-.2|G1_09:N-.2|G1_10:N-.2|G1_11:N-.2',
  '1970': 'REG:C4|IND_AP:N2*|G3_01:N-.2|G3_02:N-.2|G3_03:N-.2|G3_04:N-.2|G3_05:N-.2|G3_06:N-.2|G3_07:N-.2|G3_T:N-.2|G3_08:N-.2|G3_09:N-.2',
  '1975': 'REG:C4|ALIQ_IMP_BASE:N-.2|G3_10:N-.2|G3_11:N-.2|G3_12:N-.2',
  '1980': 'REG:C4|IND_AP:N2*|G4_01:N-.2|G4_02:N-.2|G4_03:N-.2|G4_04:N-.2|G4_05:N-.2|G4_06:N-.2|G4_07:N-.2|G4_08:N-.2|G4_09:N-.2|G4_10:N-.2|G4_11:N-.2|G4_12:N-.2',
  '1990': 'REG:C4|QTD_LIN_1:N-', // usado em agosto/2026
  '9001': 'REG:C4|IND_MOV:N1*', // usado em agosto/2026
  '9900': 'REG:C4|REG_BLC:C4|QTD_REG_BLC:N-', // usado em agosto/2026
  '9990': 'REG:C4|QTD_LIN_9:N-', // usado em agosto/2026
  '9999': 'REG:C4|QTD_LINCC:N-', // usado em agosto/2026
  'B001': 'REG:C4*|IND_DAD:C1*', // usado em agosto/2026
  'B020': 'REG|IND_OPER|IND_EMIT|COD_PART|COD_MOD|COD_SIT|SER|NUM_DOC|CHV_NFE|DT_DOC|COD_MUN_SERV|VL_CONT|VL_MAT_TERC|VL_SUB|VL_ISNT_ISS|VL_DED_BC|VL_BC_ISS|VL_BC_ISS_RT|VL_ISS_RT|VL_|COD_INF_OBS',
  'B025': 'REG:C4*|VL_CONT_P:N-.2|VL_BC_ISS_P:N-.2|ALIQ_ISS:N-.2|VL_ISS_P:N-.2|VL_ISNT_ISS_P:N-.2|COD_SERV:C4*',
  'B030': 'REG:C4*|COD_MOD:C2*|SER:C3|NUM_DOC_INI:N9|NUM_DOC_FIN:N9|DT_DOC:N8*|QTD_CANC:N-|VL_CONT:N-.2|VL_ISNT_ISS:N-.2|VL_BC_ISS:N-.2|VL_:N-.2|COD_INF_OBS:C60',
  'B035': 'REG|VL_CONT_P|VL_BC_ISS_P|ALIQ_ISS|VL_ISS_P|VL_ISNT_ISS_P|COD_SERV',
  'B350': 'REG:C4|COD_CTD:C-|CTA_ISS:C-|CTA_COSIF:N8|QTD_OCOR:N-|COD_SERV:N4|VL_CONT:N-.2|VL_BC_ISS:N-.2|ALIQ_ISS:N-.2|VL_ISS:N-.2|COD_INF_OBS:C60',
  'B420': 'REG:C4*|VL_CONT:N-.2|VL_BC_ISS:N-.2|ALIQ_ISS:N-.2|VL_ISNT_ISS:N-.2|VL_ISS:N-.2|COD_SERV:C-',
  'B440': 'REG:C4|IND_OPER:N-.2|COD_PART:C-|VL_CONT_RT:N-.2|VL_BC_ISS_RT:N-.2|VL_ISS_RT:N-.2',
  'B460': 'REG|IND_DED|VL_DED|NUM_PROC|IND_PROC|PROC|COD_INF_OBS|IND_OBR',
  'B470': 'REG|VL_CONT|VL_MAT_TERC|VL_MAT_PROP|VL_SUB|VL_ISNT|VL_DED_BC|VL_BC_ISS|VL_BC_ISS_RT|VL_|VL_ISS_RT|VL_DED|VL_|VL_|VL_ISS_REC_UNI',
  'B500': 'REG|VL_REC|QTD_PROF|VL_OR',
  'B510': 'REG:C4*|IND_PROF:C1*|IND_ESC:C1*|IND_SOC:C1*|CPF:N11*|NOME:C100',
  'B990': 'REG:C4|QTD_LIN_B:N-', // usado em agosto/2026
  'C001': 'REG:C4|IND_MOV:C1', // usado em agosto/2026
  'C100': 'REG:C4|IND_OPER:C1*|IND_EMIT:C1*|COD_PART:C60|COD_MOD:C2*|COD_SIT:N2*|SER:C3|NUM_DOC:N9|CHV_NFE:N44*|DT_DOC:N8*|DT_E_S:N8*|VL_DOC:N-.2|IND_PGTO:C1*|VL_DESC:N-.2|VL_ABAT_NT:N-.2|VL_MERC:N-.2|IND_FRT:C1*|VL_FRT:N-.2|VL_SEG:N-.2|VL_OUT_DA:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|VL_ICMS_ST:N-.2|VL_IPI:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2|VL_PIS_ST:N-.2|VL_COFINS_ST:N-.2', // usado em agosto/2026
  'C101': 'REG:C4|VL_FCP_UF_DEST:N-.2|VL_ICMS_UF_DEST:N-.2|VL_ICMS_UF_REM:N-.2',
  'C105': 'REG:C4|OPER:N1*|UF:C2*',
  'C110': 'REG:C4|COD_INF:C6|TXT_COMPL:C-', // usado em agosto/2026
  'C111': 'REG:C4|NUM_PROC:C60|IND_PROC:C1*',
  'C112': 'REG:C4|COD_DA:C1*|UF:C2*|NUM_DA:C-|COD_AUT:C-|VL_DA:N-.2|DT_VCTO:N8*|DT_PGTO:N8*',
  'C113': 'REG|IND_OPER|IND_EMIT|COD_PART|COD_MOD|SER|SUB|NUM_DOC|DT_DOC',
  'C114': 'REG:C4|COD_MOD:C2*|ECF_FAB:C21|ECF_CX:N3|NUM_DOC:N9|DT_DOC:N8*',
  'C115': 'REG:C4|IND_CARGA:N1*|CNPJ_COL:N14*|IE_COL:C14|CPF_COL:N11*|COD_MUN_COL:N7*|CNPJ_ENTG:N14*|IE_ENTG:C14|CPF_ENTG:N11*|COD_MUN_ENT:N7*',
  'C116': 'REG:C4|COD_MOD:C2|NR_SAT:N9|CHV_CFE:N44|NUM_CFE:N6|DT_DOC:N8',
  'C120': 'REG:C4|COD_DOC_IMP:C1*|NUM_DOC_IMP:C15|PIS_IMP:N-.2|COFINS:N2|NUM_ACDRAW:C20',
  'C130': 'REG:C4|VL_SERV_NT:N-.2|VL_BC_ISSQN:N-.2|VL_ISSQN:N-.2|VL_BC_IRRF:N-.2|VL_:N-.2|VL_BC_PREV:N-.2|VL_:N-.2',
  'C140': 'REG:C4|IND_EMIT:C1*|IND_TIT:C2*|DESC_TIT:C-|NUM_TIT:C-|QTD_PARC:N2|VL_TIT:N-.2',
  'C141': 'REG:C4|NUM_PARC:N2|DT_VCTO:N8*|VL_PARC:N-.2',
  'C160': 'REG:C4|COD_PART:C60|VEIC_ID:C7|QTD_VOL:N-|PESO_BRT:N-.2|PESO_LIQ:N-.2|UF_ID:C2',
  'C165': 'REG|OC',
  'C170': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|DESCR_COMPL:C-|QTD:N-.5|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2|IND_MOV:C1*|CST_ICMS:N3*|CFOP:N4*|COD_NAT:C10|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|ALIQ_ST:N-.2|VL_ICMS_ST:N-.2|IND_APUR:C1*|CST_IPI:C2*|COD_ENQ:C3*|VL_BC_IPI:N-.2|ALIQ_IPI:N6.2|VL_IPI:N-.2|CST_PIS:N2*|VL_BC_PIS:N-.2|ALIQ_PIS:N8.4|QUANT_BC_PIS:N-.3|ALIQ_PIS:N-.4|VL_PIS:N-.2|CST_COFINS:N2*|VL_BC_COFINS:N-.2|ALIQ_COFINS:N8.4|QUANT_BC_COFINS:N-.3|ALIQ_COFINS:N-.4|VL_COFINS:N-.2|COD_CTA:C-|VL_ABAT_NT:N-.2', // usado em agosto/2026
  'C171': 'REG:C4|NUM_TANQUE:C3|QTDE:N-.3',
  'C172': 'REG:C4|VL_BC_ISSQN:N-.2|ALIQ_ISSQN:N6.2|VL_ISSQN:N-.2',
  'C173': 'REG:C4|LOTE_MED:C-|QTD_ITEM:N-|DT_FAB:N8*|DT_VAL:N8*|IND_MED:C1*|TP_PROD:C1*|VL_TAB_MAX:N-.2',
  'C174': 'REG:C4|IND_ARM:C1*|NUM_ARM:C-|DESCR_COMPL:C-',
  'C175': 'REG:C4|IND_VEIC_OPER:C1*|CNPJ:N14*|UF:C2*|CHASSI_VEIC:C17',
  'C176': 'REG:C4|COD_MOD_ULT_E:C2*|NUM_DOC_ULT_E:N9|SER_ULT_E:C3|DT_ULT_E:N8*|COD_PART_ULT_E:C60|QUANT_ULT_E:N-.3|VL_UNIT_ULT_E:N-.3|VL_UNIT_BC_ST:N-.3|CHAVE_NFE_ULT_E:N44*|NUM_ITEM_ULT_E:N3|VL_UNIT_BC_ICMS:N-.2|ALIQ_ICMS_ULT_E:N-.2|VL_UNIT_LIMITE_BC_ICMS_ULT_E:N-.2|VL_UNIT_ICMS_ULT_E:N-.3|ALIQ_ST_ULT_E:N-.2|VL_UNIT_RES:N-.3|COD_RESP_RET:N1*|COD_MOT_RES:N1*|CHAVE_NFE_RET:N44*|COD_PART_NFE_RET:C60|SER_NFE_RET:C3|NUM_NFE_RET:N9|ITEM_NFE_RET:N3|COD_DA:C1*|NUM_DA:C-|VL_UNIT_RES_FCP:N-.3',
  'C177': 'REG|COD_SELO_IPI|QT_SELO_IPI',
  'C178': 'REG:C4|CL_ENQ:C5|VL_UNID:N-.2|QUANT_PAD:N-.3',
  'C179': 'REG|BC_ST_ORIG_DEST|ICMS_ST_REP|ICMS_ST_COMPL|BC_RET|ICMS_RET',
  'C180': 'REG:C4|COD_RESP_RET:N1*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_BC_ICMS_ST:N-.6|VL_UNIT_ICMS_ST_CONV:N-.6|VL_UNIT_FCP_ST_CONV:N-.6|COD_DA:C1*|NUM_DA:C-',
  'C181': 'REG|COD_MOT_REST_COMPL|QUANT_CONV|UNID|COD_MOD_SAIDA|SERIE_SAIDA|ECF_FAB_SAIDA|NUM_DOC_SAIDA|CHV_DFE_SAIDA|DT_DOC_SAIDA|NUM_ITEM_SAIDA|VL_UNIT_CONV_SAIDA|OQUE_CONV_SAIDA|OQUE_CONV_SAIDA|ESTOQUE_CONV_SAIDA|VL_UNIT_ICMS_NA_OPE|VL_UNIT_ICMS_OP_CONV_SAIDA|VL_UNIT_ICMS_ST_CONV_REST',
  'C185': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|CST_ICMS:N3*|CFOP:N4*|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_CONV:N-.6|VL_UNIT_FCP_ST_CONV_REST:N-.6|VL_UNIT_ICMS_ST_CONV:N-.6|VL_UNIT_FCP_ST_CONV_COMPL:N-.6',
  'C186': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|CST_ICMS:N3*|CFOP:N4*|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|COD_MOD_ENTRADA:C2*|SERIE_ENTRADA:C3|NUM_DOC_ENTRADA:N9|CHV_DFE_ENTRADA:N44*|DT_DOC_ENTRADA:N8*|NUM_ITEM_ENTRADA:N3|VL_UNIT_CONV_ENTRADA:N-.6|VL_UNIT_ICMS_OP_CONV_ENTRADA:N-.6|VL_UNIT_BC_ICMS_ST:N-.6|VL_UNIT_ICMS_ST_CONV_ENTRADA:N-.6|VL_UNIT_FCP_ST_CONV_ENTRADA:N-.6',
  'C190': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|VL_ICMS_ST:N-.2|VL_RED_BC:N-.2|VL_IPI:N-.2|COD_OBS:C6', // usado em agosto/2026
  'C195': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'C197': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'C300': 'REG|COD_MOD|SER|SUB|NUM_DOC_INI|NUM_DOC_FIN|DT_DOC|VL_DOC|VL_PIS|VL_COFINS|COD_CTA',
  'C310': 'REG:C4|NUM_DOC_CANC:N-',
  'C320': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_RED_BC:N-.2|COD_OBS:C6',
  'C321': 'REG:C4|COD_ITEM:C60|QTD:N-.3|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2',
  'C330': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_CONV:N-.6|VL_UNIT_FCP_ST_CONV_REST:N-.6|VL_UNIT_ICMS_ST_CONV:N-.6|VL_UNIT_FCP_ST_CONV_COMPL:N-.6',
  'C350': 'REG:C4|SER:C3|SUB_SER:C3|NUM_DOC:N6|DT_DOC:N8*|CNPJ_CPF:N14|VL_MERC:N-.2|VL_DOC:N-.2|VL_DESC:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2|COD_CTA:C-',
  'C370': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|QTD:N-.3|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2',
  'C380': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_FCP_ICMS_S:N-.6|VL_UNIT_ICMS_ST_CONV_REST:N-.6|VL_UNIT_FCP_ST_CONV_REST:N-.6|VL_UNIT_ICMS_ST_CONV_COMPL:N-.6|VL_UNIT_FCP_ST_CONV_COMPL:N-.6|CST_ICMS:N3*|CFOP:N4*',
  'C390': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_RED_BC:N-.2|COD_OBS:C6',
  'C400': 'REG:C4|COD_MOD:C2*|ECF_MOD:C20|ECF_FAB:C21|ECF_CX:N3',
  'C405': 'REG:C4|DT_DOC:N8*|CRO:N3|CRZ:N6|NUM_COO_FIN:N9|GT_FIN:N-.2|VL_BRT:N-.2',
  'C410': 'REG:C4|VL_PIS:N-.2|VL_COFINS:N-.2',
  'C420': 'REG|COD_TOT_PAR|VLR_ACUM_TOT|NR_TOT|DESCR_NR_TOT',
  'C425': 'REG:C4|COD_ITEM:C60|QTD:N-.3|UNID:C6|VL_ITEM:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2',
  'C430': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_FCP_ICMS_ST:N-.6|VL_UNIT_ICMS_ST_CONV_REST:N-.6|VL_UNIT_FCP_ST_CONV:N-.6|VL_UNIT_ICMS_ST_CONV_COMPL:N-.6|VL_UNIT_FCP_ST_CONV:N-.6|CST_ICMS:N3*|CFOP:N4*',
  'C460': 'REG:C4|COD_MOD:C2*|COD_SIT:N2*|NUM_DOC:N9|DT_DOC:N8*|VL_DOC:N-|VL_PIS:N-|VL_COFINS:N-.2|CPF_CNPJ:N-.2|NOM_ADQ:C14.2',
  'C465': 'REG:C4|CHV_CFE:N44|NUM_CCF:N9',
  'C470': 'REG:C4|COD_ITEM:C60|QTD:N-.3|QTD_CANC:N-.3|UNID:C6|VL_ITEM:N-.2|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_PIS:N-.2|VL_COFINS:N-.2',
  'C480': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA:N-.6|VL_UNIT_ICMS_OP:N-.6|VL_UNIT_ICMS_OP:N-.6|VL_UNIT_ICMS_ST_:N-.6|VL_UNIT_FCP_ICMNV:N-.6|VL_UNIT_ICMS_ST_CONV_REST:N-.6|VL_UNIT_FCP_ST_CONV_REST:N-.6|VL_UNIT_ICMS_ST_CONV_COMPL:N-.6|VL_UNIT_FCP_ST_CONV_COMPL:N-.6|CST_ICMS:N3*|CFOP:N4*',
  'C490': 'REG|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_BC_ICMS|VL_ICMS|COD_OBS',
  'C495': 'REG:C4|ALIQ_ICMS:N6.2|COD_ITEM:C60|QTD:N-.3|QTD_CANC:N-.3|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2|VL_CANC:N-.2|VL_ACMO:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_ISEN:N-.2|VL_NT:N-.2|VL_ICMS_ST:N-.2',
  'C500': 'REG|IND_OPER|IND_EMIT|COD_PART|COD_MOD|COD_SIT|SER|SUB|COD_CONS|NUM_DOC|DT_DOC|DT_E_S|VL_DOC|VL_DESC|VL_FORN|VL_SERV_NT|VL_TERC|VL_DA|VL_BC_ICMS|VL_ICMS|VL_BC_ICMS_ST|VL_ICMS_ST|COD_INF|VL_PIS|VL_COFINS|TP|COD_GRUPO_TENSAO',
  'C510': 'REG|NUM_ITEM|COD_ITEM|COD_CLASS|QTD|UNID|VL_ITEM|VL_DESC|CST_ICMS|CFOP|VL_BC_ICMS|ALIQ_ICMS|VL_ICMS|VL_BC_ICMS_ST|ALIQ_ST|VL_ICMS_ST|IND_REC|COD_PART|VL_PIS|VL_COFINS|COD_CTA',
  'C590': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_BC_ICMS_ST:N-.2|VL_ICMS_ST:N-.2|VL_RED_BC:N-.2|COD_OBS:C6',
  'C591': 'REG|VL_FCP_OP|VL_FCP_ST',
  'C595': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'C597': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'C600': 'REG|COD_MOD|COD_MUN|SER|SUB|COD_CONS|QTD_CONS|QTD_CANC|DT_DOC|VL_DOC|VL_DESC|CONS|VL_FORN|VL_SERV_NT|VL_TERC|VL_DA|VL_BC_ICMS|VL_ICMS|VL_BC_ICMS_ST|VL_ICMS_ST|VL_PIS|VL_COFINS',
  'C601': 'REG:C4|NUM_DOC_CANC:N9',
  'C610': 'REG|COD_CLASS|COD_ITEM|QTD|UNID|VL_ITEM|VL_DESC|CST_ICMS|CFOP|ALIQ_ICMS|VL_BC_ICMS|VL_ICMS|VL_BC_ICMS_ST|VL_ICMS_ST|VL_PIS|VL_COFINS|COD_CTAICMSICMS',
  'C690': 'REG|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_BC_ICMS|VL_ICMS|VL_RED_BC|VL_BC_ICMS_ST|VL_ICMS_ST|COD_OBS',
  'C700': 'REG:C4|COD_MOD:C2*|SER:C4|NRO_ORD_INI:N9|NRO_ORD_FIN:N9|DT_DOC_INI:N8*|DT_DOC_FIN:N8*|NOM_MEST:C33|CHV_COD_DIG:C32',
  'C790': 'REG|CST_ICMS|CFOP|ALIQ_ICMS',
  'C791': 'REG:C4|UF:C2*|VL_BC_ICMS_ST:N-.2|VL_ICMS_ST:N-.2',
  'C800': 'REG|COD_MOD|COD_SIT|NUM_CFE|DT_DOC|VL_CFE|VL_PIS|VL_COFINS|CNPJ_CPF|NR_SAT|CHV_CFE|VL_DESC|VL_MERC|VL_OUT_DA|VL_ICMS|VL_PIS_ST|VL_COFINS_STDV',
  'C810': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C-|QTD:N6.5|UNID:C3*|VL_ITEM:N4*.2|CST_ICMS:N-|CFOP:N-',
  'C815': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.6|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.6|VL_UNIT_ICMS_OP_CONV:N-.6|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV:N-.6|VL_UNIT_ICMS_ST_CONV_REST:N-.6|VL_UNIT_FCP_ST_CONV:N-.6|VL_UNIT_ICMS_ST_CONV_COMPL:N-.6|VL_UNIT_FCP_ST_CONV:N-.6',
  'C850': 'REG:C4|CST_ICMS:N3|CFOP:N4|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|COD_OBS:C6',
  'C855': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'C857': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'C860': 'REG:C4|COD_MOD:C2|NR_SAT:N9|DT_DOC:N8|DOC_INI:N6|DOC_FIM:N6',
  'C870': 'REG:C4|COD_ITEM:C60|QTD:N-.5|UNID:C6|CST_ICMS:N3*|CFOP:N4*',
  'C880': 'REG:C4|COD_MOT_REST_COMPL:C5*|QUANT_CONV:N-.6|UNID:C6|VL_UNIT_CONV:N-.3|VL_UNIT_ICMS_NA_OPERACAO_CONV:N-.3|VL_UNIT_ICMS_OP_CONV:N-.3|VL_UNIT_ICMS_OP_ESTOQUE_CONV:N-.3|VL_UNIT_ICMS_ST_ESTOQUE_CONV:N-.3|VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV:N-.3|VL_UNIT_ICMS_ST_CONV_REST:N-.3|VL_UNIT_FCP_ST_CONV:N-.3|VL_UNIT_ICMS_ST_CONV_COMPL:N-.3|VL_UNIT_FCP_ST_CONV:N-.3',
  'C890': 'REG:C4|CST_ICMS:N3|CFOP:N4|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|COD_OBS:C6',
  'C895': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'C897': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'C990': 'REG:C4|QTD_LIN_C:N-', // usado em agosto/2026
  'D001': 'REG:C4|IND_MOV:C1', // usado em agosto/2026
  'D100': 'REG|IND_OPER|IND_EMIT|COD_PART|COD_MOD|COD_SIT|SER|SUB|NUM_DOC|CHV_CTE|DT_DOC|DT_A_P',
  'D101': 'REG:C4|VL_FCP_UF_DEST:N-.2|VL_ICMS_UF_DES:N-.2|VL_ICMS_UF_REM:N-.2',
  'D110': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|VL_SERV:N-.2|VL_OUT:N-.2',
  'D120': 'REG:C4|COD_MUN_ORIG:N7*|COD_MUN_DEST:N7*|VEIC_ID:C7|UF_ID:C2',
  'D130': 'REG:C4|COD_PART_CONSG:C60|COD_PART_RED:C60|IND_FRT_RED:C1*|COD_MUN_ORIG:N7*|COD_MUN_DEST:N7*|VEIC_ID:C7|VL_LIQ_FRT:N-.2|VL_SEC_CAT:N-.2|VL_DESP:N-.2|VL_PEDG:N-.2|VL_OUT:N-.2|VL_FRT:N-.2|UF_ID:C2',
  'D140': 'REG:C4|COD_PART_CONSG:C60|COD_MUN_ORIG:N7*|COD_MUN_DEST:N7*|IND_VEIC:C1*|VEIC_ID:C-|IND_NAV:C1*|VIAGEM:N-|VL_FRT_LIQ:N-.2|VL_DESP_PORT:N-.2|VL_DESP_CAR_DESC:N-.2|VL_OUT:N-.2|VL_FRT_BRT:N-.2|VL_FRT_MM:N-.2',
  'D150': 'REG:C4|COD_MUN_ORIG:N7*|COD_MUN_DEST:N7*|VEIC_ID:C-|VIAGEM:N-|IND_TFA:C1*|VL_PESO_TX:N-.2|VL_TX_TERR:N-.2|VL_TX_RED:N-.2|VL_OUT:N-.2|VL_TX_ADV:N-.2',
  'D160': 'REG:C4|DESPACHO:C-|CNPJ_CPF_REM:N14|IE_REM:C14|COD_MUN_ORI:N7*|CNPJ_CPF_DEST:N14|IE_DEST:C14|COD_MUN_DEST:N7*',
  'D161': 'REG:C4|IND_CARGA:N1*|CNPJ_CPF_COL:C14|IE_COL:C14|COD_MUN_COL:N7*|CNPJ_CPF_ENTG:C14|IE_ENTG:C14|COD_MUN_ENTG:N7*',
  'D162': 'REG:C4|COD_MOD:C2*|SER:C4|NUM_DOC:N9|DT_DOC:N8*|VL_DOC:N-.2|VL_MERC:N-.2|QTD_VOL:N-|PESO_BRT:N-.2|PESO_LIQ:N-.2',
  'D170': 'REG:C4|COD_PART_CONSG:C60|COD_PART_RED:C60|COD_MUN_ORIG:N7*|COD_MUN_DEST:N7*|OTM:C-|IND_NAT_FRT:C1*|VL_LIQ_FRT:N-.2|VL_GRIS:N-.2|VL_PDG:N-.2|VL_OUT:N-.2|VL_FRT:N-.2|VEIC_ID:C7|UF_ID:C2',
  'D180': 'REG:C4|NUM_SEQ:N-|IND_EMIT:C1*|CNPJ_CPF_EMIT:N14|UF_EMIT:C2*|IE_EMIT:C14|COD_MUN_ORIG:N7*|CNPJ_CPF_TOM:N14|UF_TOM:C2*|IE_TOM:C14|COD_MUN_DEST:N7*|COD_MOD:C2*|SER:C4|SUB:N3|NUM_DOC:N9|DT_DOC:N8*|VL_DOC:N-.2',
  'D190': 'REG|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_BC_ICMS|VL_ICMS|VL_RED_BC|COD_OBS',
  'D195': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'D197': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'D300': 'REG|COD_MOD|SER|SUB|NUM_DOC_INI|NUM_DOC_FIN|CST_ICMS|CFOP|ALIQ_ICMS|DT_DOC|VL_OPR|VL_DESC|VL_SERV|VL_SEG|VL_OUT|VL_BC_ICMS|VL_ICMS|VL_RED_BC|COD_OBS|COD_CTA',
  'D301': 'REG:C4|NUM_DOC_CANC:N-',
  'D310': 'REG:C4|COD_MUN_ORIG:N7*|VL_SERV:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-',
  'D350': 'REG:C4|COD_MOD:C2*|ECF_MOD:C20|ECF_FAB:C21|ECF_CX:N3',
  'D355': 'REG:C4|DT_DOC:N8*|CRO:N3|CRZ:N6|NUM_COO_FIN:N9|GT_FIN:N-.2|VL_BRT:N-.2',
  'D360': 'REG:C4|VL_PIS:N-.2|VL_COFINS:N-.2',
  'D365': 'REG:C4|COD_TOT_PAR:C7|VLR_ACUM_TOT:N-.2|NR_TOT:N2|DESCR_NR_TOT:C-',
  'D370': 'REG:C4|COD_MUN_ORIG:N7*|VL_SERV:N-.2|QTD_BILH:N-|VL_BC_ICMS:N-.2|VL_ICMS:N-.2',
  'D390': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ISSQN:N-.2|ALIQ_ISSQN:N6.2|VL_ISSQN:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|COD_OBS:C6',
  'D400': 'REG:C4|COD_PART:C60|COD_MOD:C2*|COD_SIT:N2*|SER:C4|SUB:N3|NUM_DOC:N6|DT_DOC:N8*|VL_DOC:N-.2|VL_DESC:N-.2|VL_SERV:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2|COD_CTA:C-',
  'D410': 'REG|COD_MOD|SER|SUB|NUM_DOC_INI|NUM_DOC_FIN|DT_DOC|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_DESC|VL_SERV|VL_BC_ICMS|VL_ICMS',
  'D411': 'REG:C4|NUM_DOC_CANC:N-',
  'D420': 'REG:C4|COD_MUN_ORIG:N7*|VL_SERV:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2',
  'D500': 'REG:C4|IND_OPER:C1*|IND_EMIT:C1*|COD_PART:C60|COD_MOD:C2*|COD_SIT:N2*|SER:C4|SUB:C3|NUM_DOC:N9|DT_DOC:N8*|DT_A_P:N8*|VL_DOC:N-.2|VL_DESC:N-.2|VL_SERV:N-.2|VL_SERV_NT:N-.2|VL_TERC:N-.2|VL_DA:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|COD_INF:C6|VL_PIS:N-.2|VL_COFINS:N-|COD_CTA:C-|TP_ASSINANTE:N1*.1',
  'D510': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|COD_CLASS:N4*|QTD:N-.3|UNID:C6|VL_ITEM:N-.2|VL_DESC:N-.2|CST_ICMS:N3*|CFOP:N4*|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_BC_ICMS_UF:N-.2|VL_ICMS_UF:N-.2|IND_REC:C1*|COD_PART:C60|VL_PIS:N-.2|VL_COFINS:N-.2|COD_CTA:C-',
  'D530': 'REG:C4|IND_SERV:C1*|DT_INI_SERV:N8*|DT_FIN_SERV:N8*|PER_FISCAL:N6*|COD_AREA:C-|TERMINAL:N-',
  'D590': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_BC_ICMS_UF:N-.2|VL_ICMS_UF:N-.2|VL_RED_BC:N-.2|COD_OBS:C6',
  'D600': 'REG:C4|COD_MOD:C2*|COD_MUN:N7*|SER:C4|SUB:N3|COD_CONS:N2*|QTD_CONS:N-|DT_DOC:N8*|VL_DOC:N-.2|VL_DESC:N-.2|VL_SERV:N-.2|VL_SERV_NT:N-.2|VL_TERC:N-.2|VL_DA:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_PIS:N-.2|VL_COFINS:N-.2',
  'D610': 'REG|COD_CLASS|COD_ITEM|QTD|UNID|VL_ITEM|VL_DESC|CST_ICMS|CFOP|ALIQ_ICMS|VL_BC_ICMS|VL_ICMS|VL_BC_ICMS_UF|VL_ICMS_UF|VL_RED_BC|VL_PIS|VL_COFINS|COD_CTA',
  'D690': 'REG|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_BC_ICMS|VL_ICMS',
  'D695': 'REG:C4|COD_MOD:C2*|SER:C4|NRO_ORD_INI:N9|NRO_ORD_FIN:N9|DT_DOC_INI:N8*|DT_DOC_FIN:N8*|NOM_MEST:C33|CHV_COD_DIG:C32',
  'D696': 'REG|CST_ICMS|CFOP|ALIQ_ICMS',
  'D697': 'REG:C4|UF:C2*|VL_BC_ICMS:N-.2|VL_ICMS:N-.2',
  'D730': 'REG|CST_ICMS|CFOP|ALIQ_ICMS|VL_OPR|VL_BC_ICMS|VL_ICMS|VL_RED_BC|COD_OBS',
  'D731': 'REG:C4|VL_FCP_OP:N-.2',
  'D735': 'REG:C4|COD_OBS:C6|TXT_COMPL:C-',
  'D737': 'REG:C4|COD_AJ:C10*|DESCR_COMPL_AJ:C-|COD_ITEM:C60|VL_BC_ICMS:N-.2|ALIQ_ICMS:N6.2|VL_ICMS:N-.2|VL_OUTROS:N-.2',
  'D750': 'REG|COD_MOD|SER|DT_DOC|QTD_CONS|IND_PREPAGO|VL_DOC|VL_SERV|VL_SERV_NT|VL_TERC|VL_DESC|VL_DA|VL_BC_ICMS|VL_ICMS|VL_PIS|VL_COFINS|DED',
  'D760': 'REG:C4|CST_ICMS:N3*|CFOP:N4*|ALIQ_ICMS:N6.2|VL_OPR:N-.2|VL_BC_ICMS:N-.2|VL_ICMS:N-.2|VL_RED_BC:N-.2|COD_OBS:C6',
  'D761': 'REG:C4|VL_FCP_OP:N-.2',
  'D990': 'REG:C4|QTD_LIN_D:N-', // usado em agosto/2026
  'E001': 'REG:C4|IND_MOV:C1', // usado em agosto/2026
  'E100': 'REG:C4|DT_INI:N8*|DT_FIN:N8*', // usado em agosto/2026
  'E110': 'REG:C4|VL_TOT_DEBITOS:N-.2|VL_AJ_DEBITOS:N-.2|VL_TOT_AJ_DEBITOS:N-.2|VL_ESTORNOS_CRED:N-.2|VL_TOT_CREDITOS:N-.2|VL_AJ_CREDITOS:N-.2|VL_TOT_AJ_CREDITOS:N-.2|VL_ESTORNOS_DEB:N-.2|VL_SLD_CREDOR_ANT:N-.2|VL_SLD_APURADO:N-.2|VL_TOT_DED:N-.2|VL_ICMS_RECOLHER:N-.2|VL_SLD_CREDOR_TRANSPORTAR:N-.2|DEB_ESP:N-.2', // usado em agosto/2026
  'E111': 'REG:C4|COD_AJ_APUR:C8*|DESCR_COMPL_AJ:C-|VL_AJ_APUR:N-.2',
  'E112': 'REG:C4|NUM_DA:C-|NUM_PROC:C60|IND_PROC:C1*|PROC:C-|TXT_COMPL:C-',
  'E113': 'REG|COD_PART|COD_MOD|SER|SUB|NUM_DOC|DT_DOC|COD_ITEM|VL_AJ_ITEM',
  'E115': 'REG:C4|COD_INF_ADIC:C8*|VL_INF_ADIC:N-.2|DESCR_COMPL_AJ:C-',
  'E116': 'REG:C4|COD_OR:C3*|VL_OR:N-.2|DT_VCTO:N8*|COD_REC:C-|NUM_PROC:C60|IND_PROC:C1*|PROC:C-|TXT_COMPL:C-|MES_REF:N6*', // usado em agosto/2026
  'E200': 'REG:C4|UF:C2*|DT_INI:N8*|DT_FIN:N8*', // usado em agosto/2026
  'E210': 'REG:C4|IND_MOV_ST:C1|VL_SLD_CRED_ANT_ST:N-.2|VL_DEVOL_ST:N-.2|VL_RESSARC_ST:N-.2|VL_OUT_CRED_ST:N-.2|VL_AJ_CREDITOS_ST:N-.2|VL_RETENCAO_ST:N-.2|VL_OUT_DEB_ST:N-.2|VL_AJ_DEBITOS_ST:N-.2|VL_SLD_DEV_ANT_ST:N-.2|VL_DEDUCOES_ST:N-.2|VL_ICMS_RECOL_ST:N-.2|VL_SLD_CRED_ST_TRANSPORTAR:N-.2|DEB_ESP_ST:N-.2', // usado em agosto/2026
  'E220': 'REG:C4|COD_AJ_APUR:C8*|DESCR_COMPL_AJ:C-|VL_AJ_APUR:N-.2',
  'E230': 'REG:C4|NUM_DA:C-|NUM_PROC:C60|IND_PROC:N1*|PROC:C-|TXT_COMPL:C-',
  'E240': 'REG|COD_PART|COD_MOD|SER|SUB|NUM_DOC|DT_DOC|COD_ITEM|VL_AJ_ITEM',
  'E250': 'REG:C4|COD_OR:C3*|VL_OR:N-.2|DT_VCTO:N8*|COD_REC:C-|NUM_PROC:C60|IND_PROC:C1*|PROC:C-|TXT_COMPL:C-|MES_REF:N6*', // usado em agosto/2026
  'E300': 'REG:C4|UF:C2|DT_INI:N8*|DT_FIN:N8*',
  'E310': 'REG|IND_MOV_FCP_DIFAL|VL_SLD_CRED_ANT_DIFAL|VL_TOT_DEBITOS_DIFAL|VL_OUT_DEB_DIFAL|VL_TOT_CREDITOS_DIFAL|VL_OUT_CRED_DIFAL|VL_SLD_DEV_ANT_DIFAL|VL_DEDUCOES_DIFAL|VL_RECOL_DIFAL|VL_SLD_CRED_TRANSPORTAR_DIFAL|DEB_ESP_DIFAL|VL_SLD_CRED_ANT_FCP|VL_TOT_DEB_FCP|VL_OUT_DEB_FCP|VL_TOT_CRED_FCP|VL_OUT_CRED_FCP|VL_SLD_DEV_ANT_FCP|VL_DEDUCOES_FCP|VL_RECOL_FCP|VL_SLD_CRED_TRANSPORTAR_FCP|DEB_ESP_FCPC100D100',
  'E311': 'REG:C4|COD_AJ_APUR:C8*|DESCR_COMPL_AJ:C-|VL_AJ_APUR:N-.2',
  'E312': 'REG:C4|NUM_DA:C-|NUM_PROC:C60|IND_PROC:N1*|PROC:C-|TXT_COMPL:C-',
  'E313': 'REG|COD_PART|COD_MOD|SER|SUB|NUM_DOC',
  'E316': 'REG:C4|COD_OR:C3*|VL_OR:N-.2|DT_VCTO:N8*|COD_REC:C-|NUM_PROC:C60|IND_PROC:C1*|PROC:C-|TXT_COMPL:C-|MES_REF:N6*',
  'E500': 'REG:C4|IND_APUR:C1*|DT_INI:N8*|DT_FIN:N8*',
  'E510': 'REG:C4|CFOP:N4*|CST_IPI:C2*|VL_CONT_IPI:N-.2|VL_BC_IPI:N-.2|VL_IPI:N-.2',
  'E520': 'REG:C4|VL_SD_ANT_IPI:N-.2|VL_DEB_IPI:N-.2|VL_CRED_IPI:N-.2|VL_OD_IPI:N-.2|VL_OC_IPI:N-.2|VL_SC_IPI:N-.2|VL_SD_IPI:N-.2',
  'E530': 'REG:C4|IND_AJ:C1*|VL_AJ:N-.2|COD_AJ:C3*.5|IND_DOC:C1*|NUM_DOC:C-|DESCR_AJ:C-',
  'E531': 'REG:C4|COD_PART:C60|COD_MOD:C2*|SER:C4|SUB:N3|NUM_DOC:N9|DT_DOC:N8*|COD_ITEM:C60|VL_AJ_ITEM:N-.2|CHV_NFE:N44*',
  'E990': 'REG:C4|QTD_LIN_E:N-', // usado em agosto/2026
  'G001': 'REG:C4*|IND_MOV:C1*', // usado em agosto/2026
  'G110': 'REG:C4*|DT_INI:N8*|DT_FIN:N8*|SALDO_IN_ICMS:N-.2|SOM_PARC:N-.2|VL_TRIB_EXP:N-.2|VL_TOTAL:N-.2|IND_PER_SAI:N-.8|ICMS_APROP:N-.2|SOM_ICMS_OC:N-.2',
  'G125': 'REG:C4*|COD_IND_BEM:C60|DT_MOV:N8*|TIPO_MOV:C2*|VL_IMOB_ICMS_OP:N-.2|VL_IMOB_ICMS_ST:N-.2|VL_IMOB_ICMS_FRT:N-.2|VL_IMOB_ICMS_DIF:N-.2|NUM_PARC:N3|VL_PARC_PASS:N-.2',
  'G126': 'REG|DT_INI|DT_FIM|NUM_PARC|VL_PARC_PASS|VL_TRIB_OC|VL_TOTAL|IND_PER_SAI|VL_PARC_APROP',
  'G130': 'REG:C4|IND_EMIT:C1*|COD_PART:C60|COD_MOD:C2*|SERIE:C3|NUM_DOC:N9|CHV_NFE_CTE:N44*|DT_DOC:N8*|NUM_DA:C-',
  'G140': 'REG:C4|NUM_ITEM:N3|COD_ITEM:C60|QTDE:N-.5|UNID:C6|VL_ICMS_OP_APLICADO:N-.2|VL_ICMS_ST_APLICADO:N-.2|VL_ICMS_FRT_APLICADO:N-.2|VL_ICMS_DIF_APLICADO:N-.2',
  'G990': 'REG:C4*|QTD_LIN_G:N-', // usado em agosto/2026
  'H001': 'REG:C4|IND_MOV:C1*', // usado em agosto/2026
  'H005': 'REG:C4|DT_INV:N8*|VL_INV:N-.2|MOT_INV:C2*',
  'H010': 'REG:C4|COD_ITEM:C60|UNID:C6|QTD:N-.3|VL_UNIT:N-.6|VL_ITEM:N-.2|IND_PROP:C1*|COD_PART:C60|TXT_COMPL:C-|COD_CTA:C-|VL_ITEM_IR:N-.2',
  'H020': 'REG:C4|CST_ICMS:N3*|BC_ICMS:N2|VL_ICMS:N2',
  'H030': 'REG:C4|VL_ICMS_OP:N-.6|VL_BC_ICMS_ST:N-.6|VL_ICMS_ST:N-.6|VL_FCP:N-.6',
  'H990': 'REG:C4|QTD_LIN_H:N-', // usado em agosto/2026
  'K001': 'REG:C4|IND_MOV:C1*', // usado em agosto/2026
  'K010': 'REG:C4|IND_TP_LEIAUTE:C1*',
  'K100': 'REG:C4|DT_INI:N8|DT_FIN:N8',
  'K200': 'REG:C4|DT_EST:N8|COD_ITEM:C60|QTD:N-.3|IND_EST:C1|COD_PART:C60',
  'K210': 'REG:C4|DT_INI_OS:N8*|DT_FIN_OS:N8*|COD_DOC_OS:C30|COD_ITEM_ORI:C60|QTD_ORI:N-.6',
  'K215': 'REG:C4|COD_ITEM_DES:C60|QTD_DES:N-.6',
  'K220': 'REG:C4|DT_MOV:N8|COD_ITEM_ORI:C60|COD_ITEM_DEST:C60|QTD_ORI:N-.6|QTD_DEST:N-.6',
  'K230': 'REG:C4|DT_INI_OP:N8|DT_FIN_OP:N8|COD_DOC_OP:C30|COD_ITEM:C60|QTD_ENC:N-.6',
  'K235': 'REG:C4|DT_SAIDA:N8|COD_ITEM:C60|QTD:N-.6|COD_INS_SUBST:C60',
  'K250': 'REG:C4|DT_PROD:N8|COD_ITEM:C60|QTD:N-.6',
  'K255': 'REG:C4|DT_CONS:N8|COD_ITEM:C60|QTD:N-.6|COD_INS_SUBST:C60',
  'K260': 'REG:C4|COD_OP_OS:C30|COD_ITEM:C60|DT_SAIDA:N8*|QTD_SAIDA:N-.6|DT_RET:N8*|QTD_RET:N-.6',
  'K265': 'REG:C4|COD_ITEM:C60|QTD_CONS:N-.6|QTD_RET:N-.6',
  'K270': 'REG:C4|DT_INI_AP:N8*|DT_FIN_AP:N8*|COD_OP_OS:C30|COD_ITEM:C60|QTD_COR_POS:N-.6|QTD_COR_NEG:N-.6|ORIGEM:C1',
  'K275': 'REG|COD_ITEM',
  'K280': 'REG',
  'K290': 'REG:C4|DT_INI_OP:N8|DT_FIN_OP:N8|COD_DOC_OP:C30',
  'K291': 'REG:C4|COD_ITEM:C60|QTD:N-.6',
  'K292': 'REG:C4|COD_ITEM:C60|QTD:N-.6',
  'K300': 'REG:C4|DT_PROD:N8',
  'K301': 'REG:C4|COD_ITEM:C60|QTD:N-.6',
  'K302': 'REG:C4|COD_ITEM:C60|QTD:N-.6',
  'K990': 'REG:C4|QTD_LIN_K:N-', // usado em agosto/2026
};

const CAMPO = /^([A-Z0-9_]+)(?::([CND])(-|\d+)(\*?)(?:\.(\d+))?)?$/;

function decodificar(texto) {
  return String(texto).split('|').map((parte, i) => {
    const m = parte.match(CAMPO);
    if (!m) throw new Error('campo mal formado no leiaute: ' + parte);
    return {
      n: i + 1,
      nome: m[1],
      tipo: m[2] || null,
      tam: m[3] === undefined ? null : (m[3] === '-' ? null : Number(m[3])),
      variavel: m[2] ? m[4] === '*' : null,
      dec: m[5] === undefined ? null : Number(m[5])
    };
  });
}

const cache = new Map();

/**
 * Os campos de um registro, na ordem do leiaute. `null` se o registro não
 * existe no Guia — e null é a resposta certa: um registro que o Guia não tem
 * não pode ser escriturado, e devolver lista vazia deixaria isso passar.
 */
function camposDe(reg) {
  const chave = String(reg || '').toUpperCase();
  if (!CRU[chave]) return null;
  if (!cache.has(chave)) cache.set(chave, decodificar(CRU[chave]));
  return cache.get(chave);
}

/** Quantos campos o registro tem, conforme o Guia. `null` se não existe. */
function quantosCampos(reg) {
  const campos = camposDe(reg);
  return campos ? campos.length : null;
}

/** Todos os códigos de registro que o Guia descreve. */
function registros() {
  return Object.keys(CRU);
}

module.exports = {
  GUIA_VERSAO, GUIA_ATUALIZACAO, LEIAUTE_VERSAO, GUIA_URL,
  SEM_TIPO, NOMES_SUSPEITOS, DUPLICADOS_LEGITIMOS, NOMES_ACENTUADOS_NO_GUIA,
  CRU, camposDe, quantosCampos, registros
};
