-- =============================================================================
-- CONSOLIDADO — junta as migracoes PENDENTES para colar de uma vez no SQL
--  Editor do Supabase. Quem manda sao os arquivos de fase; o verificador
--  (scripts/verificar-migracoes.js) ignora este arquivo.
--
--  NADA PENDENTE em 22/08/2026.
--
--  A fase-AH (grupos de produtos) foi aplicada e saiu daqui.
--
--  Confira com:  npm run migracoes
-- =============================================================================
