-- =============================================================================
-- CONSOLIDADO — junta as migracoes PENDENTES para colar de uma vez no SQL
--  Editor do Supabase. Quem manda sao os arquivos de fase; o verificador
--  (scripts/verificar-migracoes.js) ignora este arquivo.
--
--  NADA PENDENTE em 24/08/2026.
--
--  A fase-AJ (transicoes de status) foi aplicada, corrigida e conferida
--  contra o banco: a funcao acerta os 10 casos e o gatilho recusa escrita
--  direta com "Transicao de status invalida".
--
--  Confira com:  npm run migracoes
-- =============================================================================
