-- =============================================================================
-- CONSOLIDADO — este arquivo só junta as migrações pendentes para colar de uma
--  vez no SQL Editor do Supabase; quem manda são os arquivos de fase, e o
--  verificador (scripts/verificar-migracoes.js) ignora este aqui.
--
--  NADA PENDENTE em 15/08/2026.
--
--  A fase-ae foi aplicada e SAIU daqui de propósito. Migração aplicada não
--  fica no pacote: o "update cfop set gera_financeiro = true" desta fase não é
--  inofensivo ao repetir — ele reescreveria em cima de qualquer ajuste que o
--  contador tenha feito à mão na classificação dos CFOPs.
--
--  Quando faltar alguma, ela volta para cá com o cabeçalho
--
--      -- >>> nome-do-arquivo.sql
--
--  e o conteúdo copiado do arquivo de fase, sem uma linha a mais nem a menos.
--
--  Confira a qualquer momento com:  npm run migracoes
-- =============================================================================
